name: SimpliciteAddons
author: roblikescake
main: net.simplicite_mc.roblikescake.simpliciteaddons.SimpliciteAddons
description: It does stuff.
version: ${project.version}-b${BUILD_NUMBER}

commands:
   bed:
      description: Teleports you to your Bed location.
      usage: /<command>
